### ISSUE TITLE
ImportError: No module named ParaView.simple

### ISSUE THREAD

**Issue by wushuangmsmw** [VictorLoren/leapmotion-paraview#1]
When I want to open the leapmotion-paraview code through paraview/Tools/python shell, there is the problem " ImportError: No module named ParaView.simple". So can you give me some advice about this problem? The vision of my paraview is 4.1.0 and my Python is 2.7.3. Thank you so much.

**Comment by MrGeislinger** [comment]
I think it comes from an old compiled original version that I had personally used. I updated the [code](https://github.com/VictorLoren/leapmotion-paraview/commit/e801aa6f6538b2a6e46d9670bebb3218e90eef41) so the code referring to `ParaView.simple` now says `paraview.simple`. This should work with ParaView's pre-compiled python shell such as `pvypython`. Hopefully this helps!
