### ISSUE TITLE
Thank you for your help! And there is another problem.

### ISSUE THREAD

**Issue by wushuangmsmw** [VictorLoren/leapmotion-paraview#2]
Thank you for your updating your code sincerely! It really worked. But there is another bug: "ImportError: No module named Leap". I guess it comes from an old version of LeapSDK that you used. My LeapSDK is 2.3.1+31549 win. So if I want to run this code, what changes should I make? Again and sincerely thank you for your help!

**Comment by MrGeislinger** [comment]
I'm not an expert in Windows, but for both my Mac and Linux machine I had to import the Python libraries into the program. I think [this link](https://developer.leapmotion.com/documentation/python/devguide/Project_Setup.html) from Leap Motion's documentation may help.
